# Use the official Node.js image from the Docker Hub
FROM node:22.5.1

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# Command to serve the application
CMD ["npm", "run", "dev"]
