services:
  backend:
    build: ./backend-cgmp
    command: npx nodemon index.js
    ports:
      - "3000:3000"  # Adjust based on your backend port
  frontend:
    build: ./frontend-cgmp
    command: npm run dev
    ports:
      - "3001:3001"  # Adjust based on your frontend port


#backend: 
#cd backend-cgmp && npx nodemon index.js
#frontend:
#cd frontend-cgmp &&  npm run dev