"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/Navigation";
import { createTheme } from "@mui/material/styles";
import Footer from "./components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const theme = createTheme({
	palette: {
		primary: {
			light: "#63AE5B",
			main: "#52964A",
			dark: "#437B3D",
			contrastText: "#fff",
		},
		secondary: {
			light: "#695E4F",
			main: "#51493D",
			dark: "#3A342C",
			contrastText: "#000",
		},
	},
});

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<meta
					name="viewport"
					content="initial-scale=1, width=device-width"
				/>
			</head>
			<body className={inter.className}>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	);
}
